- PL-1-1	Administration
- PL-1-2	Protocol Support
- PL-2-1	External Cooperation
- PL-2-2	Sponsorship Support
- PL-2-3	Scout Shop Support
- PL-3-1	Press Center
- PL-4-1	JAM Newspaper & TV
- PL-4-2	Media Center
- PL-4-3	JAM Photo/Video
- PL-4-4	JAM Social Media(Koala) 
- PG-1-1	Programme General Management
- PG-1-2	Programme IST Management
- PG-1-3	Programme Professional Management
- PG-1-4	Programme Communication
- PG-1-5	Programme Records Management
- PG-1-6	Programme Safety Support
- PG-2-1	Programme Procurement & Distribution
- PG-2-2	Programme Material Management
- PG-2-3	Programme Facility
- PG-3-1	Scouting for Life·Smart & Scientific Programme
- PG-3-2	Safe & Secure·Sustainability Programme
- PG-3-3	Culture·Tradition Programme 
- PG-3-4	Aviation Programme
- PG-3-5	Challenge Programme
- PG-3-6	On-site Aqua Programme
- PG-4-1	Over Night Programme
- PG-4-2	Daily Programme
- PG-4-3	Off-site Aqua Programme
- PG-4-4	Offi-site Adventure Programme
- PG-4-5	Off-site Transportation
- PG-5-1	NSOs Programme Support
- PG-5-2	Programme Diversity & Inclusivity Support
- PG-6-1	Event Support 
- PG-6-2	Event Service
- PG-6-3	Event Media
- PG-6-4	Special Events
- PG-7-1	Welcome Centre
- PG-7-2	HQ Operation
- PG-7-3	HoC Relation
- PG-8-1	Day Visitor
- PG-8-2	Jamtel
- PG-8-3	Special Guests
- PG-8-4	Receptions 
- PG-9-1	Pre & Post Activities
- SP-1-1	Hub-Sub Camp Programme Support
- SP-1-2	Hub-Sub Camp Communications Support
- SP-1-3	Hub-Sub Camp Facilities Management
- SP-2-1	Hub Programme
- SP-2-2	Hub Communication
- SP-2-3	Hub Facilities Management
- SP-3-1	Sub Camp Operations
- SP-3-2	Sub Camp Coordination
- SP-3-3	Sub Camp Programme
- SP-4-1	Staff Hub Management
- SP-4-2	Staff Hub Operation
- SP-4-3	Staff Hub Programme
- SP-5-1	Food Management
- SP-5-2	Staff Restaurant
- SP-5-3	Food Supply Chain
- SP-5-4	Food Safety Management
- SP-6-1	Global Support
- SP-6-2	IST Career Management
- SP-6-3	WOSM Relation
- SP-7-1	Airport
- SP-8-1	Distribution
- SP-9-1	Facilities
- SP-9-2	Charging Service
- SP-9-3	Lost & Found
- SP-9-4	Parcel Service
- SF-1-1	Response and Surveillance
- SF-1-2	Statistical Analysis
- SF-2-1	Security and Fire Response
- SF-2-2	COVID19 Test Support
- SF-2-3	COVID19 Quarantine
- SF-3-1	Access control
- SF-3-2	Patrol
- SF-3-3	CCTV
- SF-3-4	Disaster relief
- SF-4-1	Clinic
- SF-4-2	Nursing Care
- SF-4-3	Special Clinic
- SF-4-4	Epidemiology
- SF-4-5	Medical Administration
- SF-4-6	Rapid Response
- SF-4-7	Listening Ear
- SF-4-8	Liaison
- SF-5-1	Airport Transportation
- SF-5-2	Service Area Support
- SF-5-3	Jamboree Site Shuttle Bus
- SF-5-4	Special Vehicle
- SF-5-5	Bicycle Service
- SF-5-6	Motor Pool Management
- IN-1-1	Office Administration
- IN-1-2	External Cooperation
- IN-1-3	Language Support
- IN-2-1	Construction
- IN-2-2	Power Supply
- IN-2-3	Communication
- IN-2-4	Upper Facility
- IN-3-1	Cleaning
- IN-3-2	Recycling Separation
- IN-4-1	Facility Support
- IN-5-1	Environmental Preservation
- IN-6-1	Facility Inspection
- IN-7-1	Delta Planning & Facility
- IN-7-2	Food House
- IN-7-3	Ban Ki-Moon SDG Maeul
- IN-7-4	Contingent Tents
- IN-7-5	Exhibition Area
- IN-7-6	Scout Trade Corner
- IN-7-7	Inter Religious Centre
- OT-1-1	Preallocated ISTs
- OT-2-1	Finnish Sauna