- Acker-Gauchheil
- Acker-Schmalwand
- Acker-Vergissmeinnicht
- Acker-Winde
- Acker-Witwenblume
- Ackerhellerkraut
- Ackerröte
- Ackersenf
- Ackerstiefmütterchen
- Ahorn
- ÄhrigeTeufelskralle
- Akazie
- Akelei
- Alpenveilchen
- Alraune
- Amaryllis
- Ananas
- Ananas-Salbei
- Apfel
- Apfelsine
- AromatischerKaskadenthymian
- Aronstab
- Artischocke
- Arznei-Baldrian
- AsiatischeKermesbeere
- ÄstigeGraslilie
- Attich
- Aubergine
- AufrechterSauerklee
- AufrechterZiest
- Augentrost
- Avocado
- Azalee
- Bach-Nelkenwurz
- Bachbunge
- Balsamstrauch
- Bambus
- Banane
- Barbarakraut
- Bärenklau
- Bärenschote
- Bärlauch
- Bartnelke
- Basilikum
- Bauern-Jasmin
- Baumwolle
- Begonie
- BehaartesSchaumkraut
- Beifuß
- Beinwell
- Benediktinerkraut
- Berg-Sandglöckchen
- Bergenie
- Bergklee
- Bergpalme
- Betonie
- Bibernelle
- Bienenfreund
- Bilsenkraut
- Birke
- Birkenfeige
- Birkenporling
- Birne
- BitteresSchaumkraut
- BittersüßerNachtschatten
- BlassgelberLerchensporn
- Blattkaktus
- BlattkaktusEpiphyllum
- BlauerKartoffelbaum
- Blaukissen
- Blauregen
- Blutweiderich
- Blutwurz
- Bohne
- Borretsch
- Böschungsmyrthe
- Bougainvillea
- Braunelle
- Brennessel
- Brombeere
- Bromelie
- Brunnenkresse
- Buche
- Buchenporling
- Buchweizen
- BunterMajoran
- Buntnessel
- Buschwindröschen
- Calla
- Christophskraut
- Christrose
- Christusdorn
- Currykraut
- Dahlie
- DeutscherEnzian
- DeutscheSchwertlilie
- Dieffenbachie
- Dill
- Distel
- Dost
- Drachenbaum
- Duftblattpelargonie
- DuftendePlatterbse
- Duftveilchen
- Eberesche
- Eberraute
- Echeverie
- EchteAloe
- EchteHundszunge
- EchteKamille
- EchteNelkenwurz
- EchterSteinsame
- Edel-Gamander
- Edelrosen
- Efeu
- Efeutute
- Ehrenpreis
- Eiche
- Einbeere
- Einblatt
- EinjährigesBerufskraut
- EinjährigesSilberblatt
- Eisenkraut
- Elefantenfuß
- Elefantenohr
- Elfenblume
- Endivie
- Engelstrompete
- Engelwurz
- Erbse
- Erdbeer-Fingerkraut
- Erdrauch
- Espe
- Esskastanie
- Färberkamille
- Färberwaid
- Federbusch
- Feige
- Feld-Mannstreu
- Feld-Thymian
- Feldsalat
- Fenchel
- Fensterblatt
- Ferokaktus
- Fetthenne
- Feuerdorn
- Fichte
- Fichtenspargel
- Fingerhut
- Flachs
- Flamingoblume
- FlammendesKäthchen
- Flatterbinse
- Fledermausblume
- FleißigesLieschen
- Flieder
- Flockenblume
- Forsythie
- Fransenenzian
- Franzosenkraut
- FranzösischerLavendel
- Frauenflachs
- Frauenmantel
- Frauenschuh
- Freesie
- Frosch-Simse
- Frühlings-Fingerkraut
- Frühlings-Hungerblümchen
- Frühlingsenzian
- Fuchsie
- Funkie
- Futter-Esparsette
- Galia-Melone
- Gänseblümchen
- Gänsefingerkraut
- Gartenerdbeere
- Gartenkresse
- Gasterie
- Gebirgskaktus
- GefingerterLerchensporn
- GelberEisenhut
- GelbesWindröschen
- GelbeTeichrose
- Gelbsenf
- Gelbstern
- GemeineTraubenkirsche
- GemeineWaldrebe
- Gerbera
- Gerste
- GewöhnlicheSeidenpflanze
- GewöhnlichesSchilf
- GezähnterFeldsalat
- Giersch
- Gilbweiderich
- Gletscherraute
- Glockenblume
- Glücksklee
- Golddistel
- Goldkugelkaktus
- Goldregen
- Granatapfel
- Grapefruit
- Graslilie
- Greiskraut
- GroßeSterndolde
- GroßeSternmiere
- GroßesZweiblatt
- Grünlilie
- Gummibaum
- Gundelrebe
- GuterHeinrich
- Habichtskraut
- Hafer
- Händelwurz
- Hanf
- Hänge
- Haselnuss
- Haselwurz
- Hasenlattich
- Hauhechel
- Hauswurz
- Haworthie
- Heckenrose
- Heidekraut
- Heidelbeere
- Herbstanemone
- Herbstaster
- Herbstzeitlose
- Herzgespann
- Hexenkraut
- Himbeere
- Hirschzungenfarn
- Hirtentäschel
- HohlerLerchensporn
- Holunder
- Hopfen
- Hortensie
- Huflattich
- Hyazinthe
- Immergrün
- Jakobsleiter
- JapanischeZierquitte
- Johanniskraut
- JungferimGrünen
- Kaffeestrauch
- Kamelie
- Kampfereberraute
- KanadischeGoldrute
- KanadischesBerufkraut
- KanarischeGlockenblume
- Kannenpflanze
- Kapkörbchen
- Kapuzinerkresse
- Karde
- Karthäusernelke
- Kartoffel
- Kartoffelrose
- Katzen-Minze
- Kerbel
- Kiefer
- Kirsche
- Kiwi
- Klappertopf
- Klee
- KleineWasserlinse
- Klette
- Knabenkraut
- Knoblauchsrauke
- Knöterich
- KnotigeBraunwurz
- Kohl
- Kohl-Lauch
- Kohlrabi
- Kolbenfaden
- Kolkwitzie
- KöniginderNacht
- Königskerze
- Korallenbäumchen
- Korea-Minze
- Korn-Rade
- Kornblume
- Kratzbeere
- Kreuz-Labkraut
- KriechenderGünsel
- Krokus
- Kronenanemone
- Kronwicke
- Kugel-Lauch
- KugeligeTeufelskralle
- Labkraut
- Lampionblume
- Lärche
- Lauch
- Lavendel
- Leberbalsam
- Leberblümchen
- Leuchterblume
- Lichtnelke
- Liebesperlenstrauch
- Liebstöckel
- Liguster
- Linde
- Lorbeer
- Löwenmäulchen
- Löwenzahn
- Lungenkraut
- Lupine
- Luzerne
- Mädesüß
- Magnolie
- Mahonie
- Maiglöckchen
- Mais
- Majoran
- Malaienblume
- Malve
- Mammutbaum
- Mandarine
- Mangold
- Margerite
- Mariendistel
- Märzbecher
- Mauerpfeffer
- Mauerraute
- Meerrettich
- Melissen-Immenblatt
- Milzkraut
- Minze
- Mistel
- Mohn
- Möhre
- Mondviole
- Mutterkorn
- Mutterkraut
- Nachtviole
- Natternkopf
- Nelke
- Nestfarn
- NickendesLeimkraut
- Ochsenauge
- Odermennig
- Oleander
- Olive
- Oregano
- Osterglocke
- Pantoffelblume
- Papier-Maulbeere
- Paprika
- Passionsblume
- Pastinak
- Pelargonie
- Pestwurz
- Petersilie
- Petunie
- Pfaffenhütchen
- Pfeilkresse
- Pfennigbaum
- Pfennigkraut
- Pfingstrose
- Pflaume
- Phlox
- Platane
- Platterbse
- Primel
- Purpur-Pracht-
- Purpurtute
- Pyramidenpappel
- QuendelblättrigeKreuzblume
- QuirlblütigerSalbei
- Rainfarn
- Ranunkel
- Ranunkelstrauch
- Raps
- Rhabarber
- Rhododendron
- Ringelblume
- Rippenfarn
- Rittersporn
- Rizinus
- Robinie
- Rohrkolben
- RömischerWermut
- Rosmarin
- Rosskastanie
- RoteBe(e)te
- RoteHeckenkirsche
- RoteJohannisbeere
- RoterHartriegel
- Rucola
- Saatwicke
- Salat
- Salbei
- Salweide
- Samtpappel
- Samtsalbei
- Sanddorn
- Sanikel
- Sauerampfer
- Sauerklee
- SchabzigerKlee
- Schachtelhalm
- Schafgarbe
- Scharbockskraut
- ScharferHahnenfuß
- Schattenblume
- Schlangenfetthenne
- Schlehe
- Schleifenblume
- Schlüsselblume
- Schmuckkörbchen
- Schneeball
- Schneebeere
- Schneeglanz
- Schneeglöckchen
- Schnittlauch
- Schöllkraut
- SchopfigeKreuzblume
- Schuppenwurz
- Schwalbenwurz
- SchwarzäugigeSusanne
- SchwarzeEdelraute
- SchwarzeJohannisbeere
- Schwarzerle
- SchwarzerNachtschatten
- Schwarznessel
- Schwarzpappel
- Schweden-Klee
- Schwertlilie
- Seerose
- Seidelbast
- Seifenkraut
- Sellerie
- SibirischerBlaustern
- Sichel-Luzerne
- Silberblatt
- Silberimmortelle
- Silberweide
- Silberwermut
- Sommeraster
- Sommerflieder
- Sommerwurz
- Sonnenblume
- Sonnenhut
- Sonnenröschen
- Spargel
- Speise-Kürbis
- Spring-Schaumkraut
- Springkraut
- Stachelbeere
- StängelumfassendesHellerkraut
- Statice
- Steinklee
- Stellar-Pelargonie
- StengelloserEnzian
- Stiefmütterchen
- StinkendeNieswurz
- Stockrose
- Storchschnabel
- Strahlenaralie
- StrahlloseKamille
- Strauch-Fingerkraut
- Streifenfarn
- Strelitzie
- Strohblume
- Studentenblume
- Sumpf-Schwertlilie
- Sumpf-Vergissmeinnicht
- Sumpf-Ziest
- Sumpfdotterblume
- Sumpfwurz
- Taubenkropf
- Taubnessel
- Teestrauch
- Thymian
- Tillandsie
- Tollkirsche
- Tomate
- Topinambur
- TränendesHerz
- Traubenhyazinthe
- Tripmadam
- Tulpen
- Tüpfelfarn
- Türkenbundlilie
- TürkischesMuskatellersalbei
- Usambaraveilchen
- Vanilleblume
- Veilchen
- Venus-Fliegenfalle
- Venus-Frauenspiegel
- Verbene
- Vexiernelke
- Vogel-Sternmiere
- Wacholder
- Wachtelweizen
- Wald-Bingelkraut
- Wald-Hainsimse
- Wald-Vergissmeinnicht
- Wald-Wicke
- Walderdbeere
- Waldhyazinthe
- Waldmeister
- Waldvögelein
- Waldziest
- WallisWermut
- Walnuss
- Wasserhahnenfuß
- Wau
- Wegerich
- Wegrauke
- Wegwarte
- Weidenröschen
- Weigelie
- Weihnachtskaktus
- Weinbergslauch
- Weinraute
- Weinrebe
- Weißdorn
- WeißlicheHainsimse
- Weißwurz
- Weizen
- Wermut
- Wiesen-Bocksbart
- Wiesen-Kerbel
- Wiesen-Pippau
- Wiesenklee
- Wiesenknopf
- Wiesenplatterbse
- Wiesensalbei
- Wiesenschaumkraut
- WildeMöhre
- Winterling
- Wirbeldost
- Wolfsmilch
- Wollgras
- Wunderstrauch
- Zaun-Wicke
- Zaunwinde
- Zierapfel
- Zierpaprika
- Zierspargel
- Zimmerhopfen
- Zimmerlinde
- Zimmertanne
- Zinnie
- Zitrone
- Zitronenmelisse
- Zucchini
- Zuckerrübe
- ZweiblättrigerBlaustern
- ZweijährigeNachtkerze
- Zwergmispel
- Zwiebel
- Zymbelkraut